language: node_js
node_js:
  - 12.4.0
services:
  - mongodb
cache:
  directories:
    - "$HOME/.cache/yarn"
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]})'
install:
  - yarn global add jest@24.7.1 react-scripts@3.0.1 --silent
  - npm install -g codecov
matrix:
  include:
    - name: API Pipeline
      env: PACKAGE_LOCATION=api
    - name: UI Pipeline
      env: PACKAGE_LOCATION=ui
script:
  - cd $PACKAGE_LOCATION
  - yarn install
  - yarn test
  - codecov -F $PACKAGE_LOCATION
  - yarn build
